config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :particles

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/particle.rb
class Particle < ApplicationRecord
  validates :name, presence: true,
  length: { minimum: 2 }

  validates :spin, presence: true,
  length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/particles_controller.rb
class ParticlesController < ApplicationController
  def index
    @particles = Particle.all
  end

  def show
    @particle = Particle.find(params[:id])
  end

  def new
    @particle = Particle.new

  end

  def destroy
    @particle = Particle.find(params[:id])
    @particle.destroy

    redirect_to particles_path
  end

  def edit
    @particle = Particle.find(params[:id])
  end

  def update
    @particle = Particle.find(params[:id])

    if @particle.update(particle_params)
      redirect_to @particle
    else
      render 'edit'
    end
  end

  def create
    @particle = Particle.new(particle_params)
    if @particle.save
      redirect_to @particle
    else
      render 'new'
    end
  end

  private
    def particle_params
      params.require(:particle).permit(:name, :spin, :color)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/particles_helper.rb
module ParticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeRubyRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/particles/_form.html.erb
<%= form_with(model: @particle, local: true) do |form| %>
  <%# Show errors if any%>
  <% if @particle.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@particle.errors.count, "error") %> prohibited
        this particle from being saved:
      </h2>
      <ul>
        <% @particle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%# Render form %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :spin %><br>
    <%= form.text_field :spin %>
  </p>

    <p>
    <%= form.label :color %><br>
    <%= form.text_field :color %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/particles/edit.html.erb
<h1>Edit particle</h1>
<%= render 'form' %>
<%= link_to 'Back', particles_path %>

app/views/particles/index.html.erb
<h1>Listing Particles</h1>

<%= link_to 'Add new', new_particle_path %>
<br></br>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @particles.each do |particle| %>
    <tr>
      <td><%= particle.name %></td>
      <td><%= particle.spin %></td>
            <td><%= particle.color %></td>

      <td><%= link_to 'Show', particle_path(particle) %></td>
      <td><%= link_to 'Edit', edit_particle_path(particle) %></td>
      <td><%= link_to 'Destroy', particle_path(particle),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/particles/new.html.erb
<h1>This is a page to create a particle</h1>

<%= render 'form' %>

<%= link_to 'Back', particles_path %>

app/views/particles/show.html.erb
<p>
<strong>Name:</strong>
<%= @particle.name %>
</p>

<p>
<strong>Spin:</strong>
<%= @particle.spin %>
</p>

<p>
<strong>Color:</strong>
<%= @particle.color %>
</p>

<%= link_to 'Back', particles_path %>

app/views/welcome/index.html.erb
<h1>Hello, World!</h1>
<%= link_to 'Particles', controller: 'particles' %>